// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'center': string;
  'pageName': string;
  'wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
