// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clear': string;
  'errorHighlight': string;
  'errorMessage': string;
  'header': string;
  'iconWrapper': string;
  'iconWrapperRight': string;
  'input': string;
  'inputWrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
