// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottomLeft': string;
  'bottomRight': string;
  'btnContent': string;
  'defaultDisplayComponent': string;
  'list': string;
  'topLeft': string;
  'topRight': string;
}
declare var cssExports: CssExports;
export = cssExports;
