// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'horizontal': string;
  'margin': string;
  'vertical': string;
}
declare var cssExports: CssExports;
export = cssExports;
