// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'disabled': string;
  'highlighted': string;
  'icon': string;
  'rightEl': string;
  'text': string;
  'wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
