// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bouncedelay': string;
  'dotloader': string;
  'dotloader1': string;
  'dotloader2': string;
  'dotloader3': string;
}
declare var cssExports: CssExports;
export = cssExports;
