// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'disabled': string;
  'margin': string;
  'padding': string;
  'wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
