// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'a': string;
  'b': string;
  'c': string;
  'isOpen': string;
  'wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
