// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'avatarWrapper': string;
  'name': string;
  'textTop': string;
  'wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
