// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'rightEl': string;
  'wrapperDark': string;
}
declare var cssExports: CssExports;
export = cssExports;
