// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrowWrapper': string;
  'bottomLeft': string;
  'bottomRight': string;
  'check': string;
  'label': string;
  'option': string;
  'optionContent': string;
  'optionList': string;
  'optionListWrapper': string;
  'placeholderAndOther': string;
  'placeholderEmpty': string;
  'plusValue': string;
  'topLeft': string;
  'topRight': string;
  'valueRendered': string;
  'valueRenderedWrapper': string;
  'valueWrapper': string;
  'wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
