// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'base': string;
  'clear': string;
  'commonButton': string;
  'content': string;
  'dark': string;
  'error': string;
  'hasIcon': string;
  'icon': string;
  'iconOnly': string;
  'iconRight': string;
  'iconWrapper': string;
  'isExpanded': string;
  'isLoading': string;
  'lg': string;
  'loader': string;
  'noBorder': string;
  'primary': string;
  'success': string;
  'transparent': string;
  'xs': string;
}
declare var cssExports: CssExports;
export = cssExports;
