// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'avatarAction': string;
  'avatarMultiWrapper': string;
  'avatarPlaceholder': string;
  'avatarWrapper': string;
  'extraLarge': string;
  'highlighted': string;
  'info': string;
  'jumbo': string;
  'large': string;
  'larger': string;
  'name': string;
  's2': string;
  's3': string;
  's4': string;
  'small': string;
  'statusOnline': string;
  'statusWrapper': string;
  'textBottom': string;
  'textTop': string;
  'wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
